import "./globals.css";
import { ReactNode } from "react";
import PlasmicProviderClient from "../components/PlasmicProviderClient";

export const metadata = {
  title: "Highvale Events",
  description: "Generated by Next.js with Plasmic"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <PlasmicProviderClient>{children}</PlasmicProviderClient>
      </body>
    </html>
  );
}