import "./globals.css";
import { ReactNode } from "react";
import { PlasmicRootProvider } from "@plasmicapp/loader-nextjs";
import { PLASMIC } from "../plasmic-init";

export const metadata = {
  title: "Highvale Events",
  description: "Generated by Next.js with Plasmic"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <PlasmicRootProvider loader={PLASMIC}>{children}</PlasmicRootProvider>
      </body>
    </html>
  );
}
