backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

# This line should *not* be indented
publish_mode: editorial_workflow

# Media files will be stored in the repo under public/images/uploads
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # Homepage sections
  - name: "homepage"
    label: "Homepage"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "content/homepage/hero.json"
        fields:
          - {label: "Title Line 1", name: "titleLine1", widget: "string"}
          - {label: "Title Line 2 (Italic)", name: "titleLine2", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "text"}
          - {label: "Primary Button Text", name: "primaryButtonText", widget: "string"}
          - {label: "Primary Button Link", name: "primaryButtonLink", widget: "string"}
          - {label: "Secondary Button Text", name: "secondaryButtonText", widget: "string"}
          - {label: "Secondary Button Link", name: "secondaryButtonLink", widget: "string"}
          - {label: "Background Image", name: "backgroundImage", widget: "image", required: false}

      - name: "services"
        label: "Services Section"
        file: "content/homepage/services.json"
        fields:
          - {label: "Section Title", name: "sectionTitle", widget: "string"}
          - {label: "Section Subtitle", name: "sectionSubtitle", widget: "text"}
          - label: "Service Cards"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Button Text", name: "buttonText", widget: "string"}
              - {label: "Button Link", name: "buttonLink", widget: "string"}

      - name: "testimonials"
        label: "Testimonials"
        file: "content/homepage/testimonials.json"
        fields:
          - {label: "Section Title", name: "sectionTitle", widget: "string"}
          - {label: "Section Subtitle", name: "sectionSubtitle", widget: "text"}
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Content", name: "content", widget: "text"}
              - {label: "Image", name: "image", widget: "image", required: false}

      - name: "faq"
        label: "FAQ Section"
        file: "content/homepage/faq.json"
        fields:
          - {label: "Section Title", name: "sectionTitle", widget: "string"}
          - {label: "Section Subtitle", name: "sectionSubtitle", widget: "text"}
          - label: "Questions"
            name: "faqs"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "text"}

  # Weddings Page
  - name: "weddings"
    label: "Weddings Page"
    files:
      - name: "content"
        label: "Page Content"
        file: "content/weddings/content.json"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Page Subtitle", name: "pageSubtitle", widget: "text"}
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Features", name: "features", widget: "list"}
          - label: "Pricing Tiers"
            name: "pricing"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Featured", name: "featured", widget: "boolean", default: false}

  # Private Events Page
  - name: "private-events"
    label: "Private Events Page"
    files:
      - name: "content"
        label: "Page Content"
        file: "content/private-events/content.json"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Page Subtitle", name: "pageSubtitle", widget: "text"}
          - label: "Event Types"
            name: "eventTypes"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Examples", name: "examples", widget: "list"}
              - {label: "Icon", name: "icon", widget: "select", options: ["Gift", "Heart", "Utensils", "Snowflake", "Music", "Flower"]}

  # Portfolio
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["weddings", "corporate", "private"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Season", name: "season", widget: "select", options: ["Spring", "Summer", "Fall", "Winter"]}
      - {label: "Guest Count", name: "guests", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Team Members
  - name: "team"
    label: "Team Members"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Expertise", name: "expertise", widget: "list"}
      - {label: "Order", name: "order", widget: "number"}

  # Company Information
  - name: "settings"
    label: "Company Settings"
    files:
      - name: "general"
        label: "General Information"
        file: "content/settings/general.json"
        fields:
          - {label: "Company Name", name: "companyName", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address Line 1", name: "addressLine1", widget: "string"}
          - {label: "Address Line 2", name: "addressLine2", widget: "string"}
          - {label: "Office Hours", name: "officeHours", widget: "text"}
          - label: "Social Media"
            name: "socialMedia"
            widget: "object"
            fields:
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
              - {label: "Pinterest", name: "pinterest", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
